name: Simple DevSecOps Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ------------------------
      # 1. Setup Python & Install Dependencies
      # ------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # ------------------------
      # 2. Run Unit Tests
      # ------------------------
      - name: Run tests
        run: pytest

      # ------------------------
      # 3. SAST (basic with Flake8)
      # ------------------------
      - name: Run Flake8 SAST
        run: flake8 .

      # ------------------------
      # 4. Build Docker Image
      # ------------------------
      - name: Build Docker image
        run: docker build -t devsecops-simple .

      # ------------------------
      # 5. Trivy Scan (Dependencies + Image)
      # ------------------------
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: devsecops-simple
          severity: HIGH,CRITICAL
          exit-code: '0'
